### ISSUE TITLE
Add reservations functionality

### ISSUE THREAD

**Issue by Smedzlatko** [treelogic-swe/aws-mock#30]
I know that this is a huge request and I am aware that this project was not very active for the past months but I am still curious whether you are still investing time to the development of this nice mock.

I am currently in need of some EC2 sandbox which would simulate running instances and reservations (buying, selling, moving, merging, splitting and assigning them to the instances). Do you, by any chance, plan to add the reservations functionality to this project?

**Comment by maxiaohao** [comment]
Hi, 
Sorry for now we aren't planning on doing such big new features, but would love to accept any pull request that had good tests we can run to verify that it works!
Thank you!

**Comment by christopherbalz** [comment]
@Smedzlatko - Just to clarlify, if you want to build reservations functionality, we would love to accept the pull request!  As long as it has good test coverage and tests that pass, we'll accept it!

**Comment by Smedzlatko** [comment]
@christopherbalz  Thank you for your answer. I will see it I have time to code something regarding this issue. Anyway, we can consider this issue closed :)
