### ISSUE TITLE
Pagination support for describeInstancesAPI in aws-mock

### ISSUE THREAD

**Issue by sdiwan** [treelogic-swe/aws-mock#35]
- While working with the real AWS setting result limits on the request allows to get records in a paginated way. Those same requests have no impact when working with aws-mock which returns ALL the data in one shot.

- This makes testing between aws and aws-mock inconsistent and also the value addition from aws-mock very limited.

- I looked at the wiki pages and did not see any mention of pagination. Is there support for this already? or any thoughts around getting this done?

- This is the way we are using pagination against the real AWs

        DescribeInstancesRequest request = new DescribeInstancesRequest();
        request.setMaxResults(getQueryPageSize());

- When the same request is being sent to aws-mock, the result limit is not being honored.

**Comment by maxiaohao** [comment]
Hi sidwan, 
Thanks for your attention to aws-mock! 
This is a reasonable request and we will try to add request.setMaxResults() and implement the pagination in response soon.

**Comment by sdiwan** [comment]
Great! Thanks a lot! Much appreciated

**Comment by maxiaohao** [comment]
Hi, 
We have released aws-mock 1.0.2 which includes full test code coverage as well as pagination feature you requested!
We also welcome any further contribution from your team - thanks!

**Comment by sdiwan** [comment]
Thanks a lot for adding this feature. We are taking the latest code and are in the process of testing it out. Also, we are adding new REST API endpoints in aws-mock and should have a review out soon for those soon.
