### ISSUE TITLE
Change cxf-stub as a "chained" built dependency of aws-mock

### ISSUE THREAD

**Issue by maxiaohao** [treelogic-swe/aws-mock#44]
We need to stop publishing cxf-stub.jar to MavenCentral and always build it as a child dependency along with aws-mock instead, because cxf-stub is only used by aws-mock.
The cxf-stub will be changed into a child project of its parent, aws-mock and each time we do a "chained" build of aws-mock, cxf-stub would be built as one of aws-mock's dependencies.

**Comment by nottoseethesun** [comment]
Could this issue now be closed then, due to the pr #42 having been merged?

**Comment by nottoseethesun** [comment]
Functionality merged.
