### ISSUE TITLE
Outdated Plugin

### ISSUE THREAD

**Issue by rhkiswani** [treelogic-swe/aws-mock#47]
Hi,
please check the warning below.

The Jetty plugin has been deprecated and is scheduled to be removed in Gradle 4.0. Consider using the Gretty (https://github.com/akhikhl/gretty) plugin instead.
        at build_6rcy6ik4hnwrmsvsif8w04xl7.run(/home/ubuntu/api/source/vendor/aws-mock/build.gradle:19)

Thanks
Mohamed

**Comment by nottoseethesun** [comment]
The current Gradle we use works fine and unless someone wants to submit a PR, we don't plan to upgrade it unless necessary for security.  We do welcome pr's for upgrades, though.
